### ISSUE TITLE
Met with "Segmentation fault (core dumped)" when using "python -m tools.run_rl ......"

### ISSUE THREAD

**Issue by shen-hhao** [haosulab/ManiSkill-Learn#1]
I installed ManiSkill benchmark and ManiSkill-Learn as instructed.
While I was running the evaluation and training code provided in README, I encountered this error in the following picture.
I was running the code on a remote server and there was the error. When I used this code on PC, the error did not occur.
I use gdb to debug the running process, and the result is pasted in gdb.txt.
![35bffd2195b9f47ac9e22a46a9ec5f3](https://user-images.githubusercontent.com/88179656/128118388-48a32cf8-398b-43c5-9cb3-120a69c791ca.png)
[gdb.txt](https://github.com/haosulab/ManiSkill-Learn/files/6928416/gdb.txt)

**Comment by fbxiang** [comment]
You can try setting the environment variable `VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json`.
Make sure the file `/usr/share/vulkan/icd.d/nvidia_icd.json` exists.

**Comment by shen-hhao** [comment]
Thanks, it worked.
