### ISSUE TITLE
Understanding the LEVEL parameter in env

### ISSUE THREAD

**Issue by harryzhangOG** [haosulab/ManiSkill-Learn#10]
Hi, I have some trouble understanding the purpose of the level parameter when resetting an environment. What aspects of the env does the level parameter randomize? For evaluating an agent trained on one env with say 100 levels, is testing on 20 unseen levels of the same env a valid evaluation process? Thanks.

**Comment by xuanlinli17** [comment]
Please see `2.1: Basic Terminlogies and Setup`, and `Appendix B.2, Environment Parameters` in our paper (https://arxiv.org/abs/2107.14483). For different levels (environment parameters), the robot's in-plane position and orientation, along with physical parameters (such as joint friction in all tasks, position & orientation of chair/bucket), are randomized.
