### ISSUE TITLE
Unsuccessful SAC training for demo generation

### ISSUE THREAD

**Issue by harryzhangOG** [haosulab/ManiSkill-Learn#11]
Hi, we made a new environment with just a floating gripper, and we are trying to generate demo data with a SAC agent. However, we found that for opening-door task, when the handle is "horizontal", SAC agent fails to succeed after training (as seen in video below, on env 1001 and 1002). I have also attached the command I was using. I switched the seed from 0 to 10 and still didn't work. Please advise if we have done anything wrong. Thanks.

`python -m tools.run_rl configs/sac/sac_mani_skill_state_1M_train.py --seed=10 --cfg-options \"env_cfg.env_name={}\" \"rollout_cfg.type=Rollout\" \"rollout_cfg.num_procs=1\" \"eval_cfg.num_procs=1\" --gpu-ids=1".format(gripper_env)`

![ezgif com-gif-maker](https://user-images.githubusercontent.com/43732483/136681712-f26c4841-affc-456d-a38e-f85c0f3a67e8.gif)

**Comment by harryzhangOG** [comment]
sorry, just updated with a new gif.

**Comment by xuanlinli17** [comment]
What was your reward function?

**Comment by harryzhangOG** [comment]
I just used the default dense reward

**Comment by xuanlinli17** [comment]
You can use `env.reset(level=some_level)` to reset the level to a level in demo.

(this is similar to `https://github.com/haosulab/ManiSkill-Learn/blob/main/tools/convert_state.py`)

**Comment by harryzhangOG** [comment]
Is there a way to do it in evaluation? We have a demo trajectory and want to train on the demo trajectory and test on the same level as a sanity check in eval. Thanks.

**Comment by xuanlinli17** [comment]
modify `evaluation.py`, like https://github.com/haosulab/ManiSkill-Learn/blob/8d968d26e59b621e02c7fdb1522ec2108c8c4f1a/mani_skill_learn/env/evaluation.py#L115

**Comment by harryzhangOG** [comment]
ok, thanks. That's what we thought.
