### ISSUE TITLE
Input to Pretrained Models

### ISSUE THREAD

**Issue by arjung128** [haosulab/ManiSkill-Learn#16]
Can the pretrained RL checkpoints be applied to RGB images from visualizer? Or does the input need to be RGBD, and if so, how do we obtain the depth information?

**Comment by xuanlinli17** [comment]
The pretrained RL checkpoints are for point cloud inputs (i.e. `env.set_env_mode('pointcloud')`). You may generate RGB-D demonstrations via https://github.com/haosulab/ManiSkill-Learn#generating-rgb-d-demonstrations , and then retrain a model via RGB-D. Note that RGB-D data will be very large, so you may need some compression (i.e. compress RGB into uint-8 and discretize depth into uint16 when saving data, and recover the data into float when training)

**Comment by arjung128** [comment]
I see, thanks!
