### ISSUE TITLE
Gym Interface for Motion Planning

### ISSUE THREAD

**Issue by arjung128** [haosulab/ManiSkill-Learn#19]
The action space of the `OpenCabinetDrawer_1045_link_0-v0` gym environment is 13-dimensional. Presumably each one of the 13 numbers corresponds to each one of the 13 joints, but what exactly is the interpretation of this?

The motion planner returns the position, velocity, and acceleration for each of the 13 joints. I am trying to determine whether the gym interface can be used to evaluate trajectories produced by motion planning (given target waypoints).

**Comment by xuanlinli17** [comment]
We recently updated a description of input robot state (agent) vector [here](https://github.com/haosulab/ManiSkill/wiki/Detailed-Explanation-of-The-Agent-State-Vector). The action space correspond to the controllable joints [here](https://github.com/haosulab/ManiSkill/blob/main/mani_skill/assets/config_files/robots/mobile_a2_single_arm.yml). All joints except finger use velocity control. Finger joints use position control.

**Comment by arjung128** [comment]
This is very helpful, thank you!
