### ISSUE TITLE
State Dataset: Explanation of keys

### ISSUE THREAD

**Issue by paulawulkop** [haosulab/ManiSkill-Learn#21]
I looked into the state dataset and I was wondering if there is an explanation anywhere how the values for those keys are defined:

['actions', 'dones', 'env_levels', 'env_scene_states', 'env_states', 'episode_dones', 'info_angle1', 'info_angle2', 'info_dist_ee_mid_to_handle', 'info_dist_ee_to_handle', 'info_eval_info_cabinet_static', 'info_eval_info_open_enough', 'info_eval_info_success', 'info_gripper_ang_vel_norm', 'info_gripper_angle_err', 'info_gripper_angle_rew', 'info_gripper_vel_norm', 'info_keep_threshold', 'info_qpos', 'info_qpos_rew', 'info_qvel', 'info_qvel_rew', 'info_rew_ee_handle', 'info_rew_ee_mid_handle', 'info_reward_raw', 'info_stage_reward', 'info_target_qpos', 'next_env_levels', 'next_env_scene_states', 'next_env_states', 'next_obs', 'obs', 'rewards']

Thanks!

**Comment by xuanlinli17** [comment]
The state dataset is used to reconstruct the corresponding environment state at a particular time step, which is used to render visual inputs as in [here](https://github.com/haosulab/ManiSkill-Learn/blob/main/tools/convert_state.py). You can refer to the file for its usage. You may ignore anything that starts with `info`.

**Comment by paulawulkop** [comment]
Thanks
