### ISSUE TITLE
OSError: /usr/lib64/libm.so.6: version `GLIBC_2.27' not found 

### ISSUE THREAD

**Issue by liu666666** [haosulab/ManiSkill-Learn#22]
Thanks for the great project!
I run this project well on ubuntu 18.04. However,  I met an error when run the training script on a new server which is equipped with Red Hat 4.8.5-28. The error happens when run the "import open3d".
The details are following: 
python -c "import open3d"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/export/home/cxd/anaconda3/lib/python3.7/site-packages/open3d/__init__.py", line 64, in <module>
    _CDLL(next((_Path(__file__).parent / 'cpu').glob('pybind*')))
  File "/export/home/cxd/anaconda3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib64/libm.so.6: version `GLIBC_2.27' not found (required by /export/home/cxd/anaconda3/lib/python3.7/site-packages/open3d/cpu/pybind.cpython-37m-x86_64-linux-gnu.so)

How to fix this? Thanks!

**Comment by lz1oceani** [comment]
I suggest you to use ubuntu 18.04 or ubuntu 20.04. Here is a link from open3d https://github.com/isl-org/Open3D/issues/1307). It seems that open3d is not supported on some old systems.
