### ISSUE TITLE
Number of training object instances

### ISSUE THREAD

**Issue by arjung128** [haosulab/ManiSkill-Learn#23]
Table 1 in the paper reports that there are 25 objects and 49 drawers in the training set of the OpenCabinetDrawer task. However, the [Google Drive link](https://drive.google.com/drive/folders/1ZD-frITTmkHGnVR3zCe56N9vybaJtKy7) only seems to contain 42 files, and not 49 -- why is this the case?

Thanks!

**Comment by lz1oceani** [comment]
Sorry for not clear in the paper. For these 25 objects, we can solve at least one link on the object. We release all links over these 25 objects, so you see 49 drawers in total.

But for some links on the objects, it is not easy to get demo by state-based SAC with limited time. So we only provide partial of them. In the challenge, we only test the object link with demo for training part.

**Comment by arjung128** [comment]
Got it, thanks!
