### ISSUE TITLE
Can you provide pretrained results of other algorithms, like BCQ and TD3+BC, and pretrained result of BC + PointNet?

### ISSUE THREAD

**Issue by zhanghuzhenyu** [haosulab/ManiSkill-Learn#25]
Can you provide pretrained results of other algorithms, like BCQ and TD3+BC, and pretrained result of BC + PointNet? I want to evaluate the accuracy of the algorithm in the article.

**Comment by xuanlinli17** [comment]
Results are presented in table 3 of our [paper](https://arxiv.org/pdf/2107.14483.pdf). The table is also attached in readme. Scripts to train the models are in `/scripts/full_mani_skill_example` for each algorithm using PointNet + Transformer over segmentation. To train PointNet models for BC you need to modify the config to be `configs/bc/mani_skill_point_cloud.py`

If you want pretrained models, I have uploaded some more to our [drive](https://drive.google.com/drive/u/2/folders/1H28oLQdP4TtsLVN7dQPmdkAO4IjyYTGl). Note that the models are from a single run and might deviate from the performance over several runs.

**Comment by zhanghuzhenyu** [comment]
This is what I need, thank you so much!!
