### ISSUE TITLE
Pointcloud data is not exactly the same as state data?

### ISSUE THREAD

**Issue by arjung128** [haosulab/ManiSkill-Learn#26]
I downloaded the point cloud data from [here](https://drive.google.com/drive/folders/1A7_WsbABXUpTKZiyoSuXpNvpIT-fNRpl) and the state data from [here](https://drive.google.com/drive/u/1/folders/10KlIo7DIyMWUxc_NXarKcjPmaXyKJivo) and tried the following:

```
import h5py

pc_data = h5py.File('full_mani_skill_data/OpenCabinetDrawer/OpenCabinetDrawer_1000_link_0-v0.h5', 'r')
state_data = h5py.File('full_mani_skill_state_data/OpenCabinetDrawer_state/OpenCabinetDrawer_1000_link_0-v0.h5', 'r')

print((pc_data['traj_10']['actions'][:] == state_data['traj_10']['actions'][:]).all())
```

And this prints `False`. Why is this the case? Were the two datasets generated separately?

**Comment by lz1oceani** [comment]
Actually, the index is different. I sort the index of state demo (like 'traj_xxx') and regenerate the index with the sorted original index, so the order is not the same ('traj_9' > 'traj_10'). You can check tools/convert_state.py and construct the index map.

**Comment by arjung128** [comment]
Got it, thanks you so much for the prompt response!

Also, I'm not sure why the robot states are not lining up over time:

```
timestep = 0
print((pc_data['traj_0']['obs']['state'][timestep] == state_data['traj_0']['env_states'][timestep, 37:75]).all())
```

This prints `True` when `timestep=0`, but `False` otherwise... This is the case for all trajectory pairs, e.g. (`pc_data['traj_1']`, `state_data['traj_1']`) or (`pc_data['traj_2']`, `state_data['traj_10']`), etc... Why is this the case?

**Comment by lz1oceani** [comment]
You can try
```
x = ['traj_{i}' for i in range(300)]
sorted(x)
```
Then x[i] will be relabelled to 'traj_{i}' in the pointcloud demo. You can print x, then you will know the mapping.

**Comment by arjung128** [comment]
Yes, I understand that. With the mapping, `pc_data['traj_0']` gets mapped to `state_data['traj_0']`, `pc_data['traj_2']` gets mapped to `state_data['traj_10']`, etc...

But what I'm not sure about is why the robot states are not lining up over time for trajectories which map to one another, e.g. (`pc_data['traj_0']` and `state_data['traj_0']`):

```
import h5py

pc_data = h5py.File('full_mani_skill_data/OpenCabinetDrawer/OpenCabinetDrawer_1000_link_0-v0.h5', 'r')
state_data = h5py.File('full_mani_skill_state_data/OpenCabinetDrawer_state/OpenCabinetDrawer_1000_link_0-v0.h5', 'r')

timestep = 0
print((pc_data['traj_0']['obs']['state'][timestep] == state_data['traj_0']['env_states'][timestep, 37:75]).all())
```

This prints `True` when `timestep=0`, but `False` otherwise... This is the case for all trajectory pairs, e.g. (`pc_data['traj_1']`, `state_data['traj_1']`) or (`pc_data['traj_2']`, `state_data['traj_10']`), etc... Why is this the case?

**Comment by lz1oceani** [comment]
Could you check the error?  It may be from the floating error.

**Comment by arjung128** [comment]
```
>>> timestep = 10
>>> np.abs((pc_data['traj_0']['obs']['state'][timestep] - state_data['traj_0']['env_states'][timestep, 37:75])).max()
```

prints `0.0002738889306783676`, which is ~`2.74e-4` ... doesn't this seem a little too large for floating point error? Although this may be floating point error if lots of operations were used...?

**Comment by lz1oceani** [comment]
OK. I think the error is very small. It may be from the simulator. 1e-4 mean 0.1 mm in 3D space. Because values like quaternions need to be normalized in the simulator. A small difference may be generated within this procedure. Also, there are float32 and float64 conversion during the computation.

**Comment by arjung128** [comment]
I see. Thanks!
