### ISSUE TITLE
Some Points on the Arm are Masked as Points on the Cabinet

### ISSUE THREAD

**Issue by Derick317** [haosulab/ManiSkill-Learn#29]
<img width="349" alt="4753dd1bfea3693cad659b32b1cf749" src="https://user-images.githubusercontent.com/90669189/175971572-3bc7b828-7359-4595-ac6e-7b741e5f4511.png">

I found some points on the arm are masked as points on the cabinet when running `open-cabinet-door` and `open-cabinet-drawer` environment. After running `env.get_obs()`, downloading the `xyz` and `seg` in the `pointcloud` and visualizing it in `matplotlib`, I got the image above. Anyone who would like to check the visualization could run the code in the `issue.zip`.
[issue.zip](https://github.com/haosulab/ManiSkill-Learn/files/8993104/issue.zip)

**Comment by xuanlinli17** [comment]
https://github.com/haosulab/ManiSkill-Learn/blob/9742da932448a5234222cf94381ca0f861dc83fd/mani_skill_learn/env/observation_process.py#L60

The bug came from this line. `np.logical_or` can only take 2 arrays at a time and not an arbitrary number of arrays. For reproducing original result purposes I'll not modify the original code, but I'll make a note in readme. You are free to fix it.

**Comment by xuanlinli17** [comment]
to fix it change it to `~seg.any(-1, keepdims=True)`

**Comment by xuanlinli17** [comment]
In fact, the robot points' segmentation will be removed with this bug and be viewed the same as the background. For a cabinet, only the handle and the board have segmentations. The back side of the cabinet does not have any segmentation and is treated as background.

**Comment by Derick317** [comment]
Thanks a lot! And we find that replacing
``` python
if seg.shape[1] == 1:
    bk_seg = np.logical_not(seg[:, 0])
else:
    bk_seg = np.logical_not(np.logical_or(*([seg[:, i] for i in range(seg.shape[1])])))
```
with
```python
if seg.shape[1] == 1:
    bk_seg = np.logical_not(seg[:, 0])
else:
    for i in range(seg.shape[1] - 1):
        if i == 0:
            bk = np.logical_or(seg[:, 0], seg[:, 1])
            continue
        bk = np.logical_or(bk, seg[:, i + 1])
    bk_seg = np.logical_not(bk)
```
is also okey!
