### ISSUE TITLE
Demonstration Data State Vector

### ISSUE THREAD

**Issue by harryzhangOG** [haosulab/ManiSkill-Learn#7]
Hi, may I ask what each element in the demo data state vector of the observation represents? Specifically, we are interested in the EE positions and poses in the trajectory. Thanks.

**Comment by xuanlinli17** [comment]
https://github.com/haosulab/ManiSkill/blob/893cc416bfc92cf334c7e7cc23c709656ed39cc6/mani_skill/agent/agent.py#L213

This is the state (or agent state) for the robot agent provided in the demonstrations. It consists of `ee_pos`, `ee_vel`, `qpos`, `qvel`, and miscellaneous controller states.
